; hKeysHeld, hKeysPressed
A_BUTTON EQU %00000001
B_BUTTON EQU %00000010
SELECT   EQU %00000100
START    EQU %00001000
D_RIGHT  EQU %00010000
D_LEFT   EQU %00100000
D_UP     EQU %01000000
D_DOWN   EQU %10000000

A_BUTTON_BIT EQU 0
B_BUTTON_BIT EQU 1
SELECT_BIT   EQU 2
START_BIT    EQU 3
D_RIGHT_BIT  EQU 4
D_LEFT_BIT   EQU 5
D_UP_BIT     EQU 6
D_DOWN_BIT   EQU 7

; hGameState
STATE_GAMEPLAY                      EQU 0
STATE_GAME_OVER                     EQU 1
STATE_04                            EQU 4
STATE_05                            EQU 5
STATE_LOAD_TITLESCREEN              EQU 6
STATE_TITLESCREEN                   EQU 7
STATE_LOAD_MODE_SELECT              EQU 8
STATE_09                            EQU 9
STATE_LOAD_PLAYFIELD                EQU 10
STATE_MODE_SELECT                   EQU 14
STATE_MUSIC_SELECT                  EQU 15
STATE_LOAD_TYPE_A_MENU              EQU 16
STATE_TYPE_A_MENU                   EQU 17
STATE_LOAD_TYPE_B_MENU              EQU 18
STATE_TYPE_B_LEVEL_SELECT           EQU 19
STATE_TYPE_B_HIGH_SELECT            EQU 20
STATE_HIGHSCORE_ENTER_NAME          EQU 21
STATE_22                            EQU 22
STATE_24                            EQU 24
STATE_26                            EQU 26
STATE_27                            EQU 27
STATE_34                            EQU 34
STATE_35                            EQU 35
STATE_LOAD_COPYRIGHT                EQU 36
STATE_COPYRIGHT                     EQU 37
STATE_LOAD_MULTIPLAYER_MUSIC_SELECT EQU 42
STATE_43                            EQU 43
STATE_MORE_COPYRIGHT                EQU 53 ; INTERNATIONAL only

; hMasterSlave
SERIAL_MASTER EQU $29
SERIAL_SLAVE  EQU $55

SERIAL_MUSIC_ACK  EQU $39
SERIAL_MUSIC_DONE EQU $50

; hSerialState
SERIAL_STATE_TITLESCREEN EQU 0
SERIAL_STATE_1           EQU 1
SERIAL_STATE_2           EQU 2
SERIAL_STATE_3           EQU 3

; wPlaySong, wCurSong
SONG_HIGHSCORE      EQU 1
SONG_B_END_JINGLE   EQU 2
SONG_TITLESCREEN    EQU 3
SONG_A_END_JINGLE   EQU 4
SONG_A              EQU 5
SONG_B              EQU 6
SONG_C              EQU 7
SONG_TENSE          EQU 8
SONG_MULTIPLAYER_JIGNLE EQU 9
SONG_ENDING         EQU 16
SONG_STOP EQU $ff

; wPlayPulseSFX, wCurPulseSFX
PULSESFX_CURSOR_BEEP  EQU 1
PULSESFX_CONFIRM_BEEP EQU 2
PULSESFX_ROTATE       EQU 3
PULSESFX_MOVE_PIECE   EQU 4
PULSESFX_LINE_CLEAR   EQU 6
PULSESFX_TETRIS       EQU 7
PULSESFX_LEVELUP      EQU 8

; wPlayWaveSFX, wCurWaveSFX
WAVESFX_GAME_OVER EQU 2

; wPlayNoiseSFX, wCurNoiseSFX
NOISESFX_LINE_REMOVED EQU 1
NOISESFX_LOCKDOWN     EQU 2

SPRITEPOS_CURRENT_TETROMINO EQU 0
SPRITEPOS_NEXT_TETROMINO    EQU 1
; wSpriteList
SPRITE_SIZE      EQU 16
SPRITE_INFO_SIZE EQU 7 ; the 9 bytes is padding
SPRITE_OFFSET_VISIBILITY EQU 0
SPRITE_OFFSET_Y          EQU 1
SPRITE_OFFSET_X          EQU 2
SPRITE_OFFSET_ID         EQU 3
SPRITE_OFFSET_BELOW_BG   EQU 4
SPRITE_OFFSET_FLIP       EQU 5
SPRITE_OFFSET_FLAGS      EQU 6

;  SPRITE_OFFSET_VISIBILITY
SPRITE_HIDDEN  EQU $80
SPRITE_VISIBLE EQU $00

;  SPRITE_OFFSET_ID
SPRITE_ID_ROTATION_MASK EQU $03

SPRITE_L0      EQU $00
SPRITE_L1      EQU $01
SPRITE_L2      EQU $02
SPRITE_L3      EQU $03
SPRITE_J0      EQU $04
SPRITE_J1      EQU $05
SPRITE_J2      EQU $06
SPRITE_J3      EQU $07
SPRITE_I0      EQU $08
SPRITE_I1      EQU $09
SPRITE_I2      EQU $0a
SPRITE_I3      EQU $0b
SPRITE_O0      EQU $0c
SPRITE_O1      EQU $0d
SPRITE_O2      EQU $0e
SPRITE_O3      EQU $0f
SPRITE_Z0      EQU $10
SPRITE_Z1      EQU $11
SPRITE_Z2      EQU $12
SPRITE_Z3      EQU $13
SPRITE_S0      EQU $14
SPRITE_S1      EQU $15
SPRITE_S2      EQU $16
SPRITE_S3      EQU $17
SPRITE_T0      EQU $18
SPRITE_T1      EQU $19
SPRITE_T2      EQU $1a
SPRITE_T3      EQU $1b
SPRITE_TYPE_A  EQU $1c
SPRITE_TYPE_B  EQU $1d
SPRITE_TYPE_C  EQU $1e
SPRITE_OFF     EQU $1f
SPRITE_DIGIT_0 EQU $20
SPRITE_DIGIT_1 EQU $21
SPRITE_DIGIT_2 EQU $22
SPRITE_DIGIT_3 EQU $23
SPRITE_DIGIT_4 EQU $24
SPRITE_DIGIT_5 EQU $25
SPRITE_DIGIT_6 EQU $26
SPRITE_DIGIT_7 EQU $27
SPRITE_DIGIT_8 EQU $28
SPRITE_DIGIT_9 EQU $29

;  SPRITE_OFFSET_BELOW_BG
SPRITE_ABOVE_BG EQU $00
SPRITE_BELOW_BG EQU $80

;  SPRITE_OFFSET_FLIP
SPRITE_DONT_FLIP EQU $00

; hGameType
GAME_TYPE_A EQU $37
GAME_TYPE_B EQU $77

; hMusicType
MUSIC_TYPE_A EQU SPRITE_TYPE_A
MUSIC_TYPE_B EQU SPRITE_TYPE_B
MUSIC_TYPE_C EQU SPRITE_TYPE_C
MUSIC_OFF    EQU SPRITE_OFF

; hDemoNumber
DEMO_NOT    EQU 0
DEMO_TYPE_B EQU 1
DEMO_TYPE_A EQU 2

; hRecordDemo
DEMO_PLAY   EQU 0
DEMO_RECORD EQU $ff

; hLockdownStage
LOCKDOWN_STAGE_IDLE                EQU 0
LOCKDOWN_STAGE_TRANSFER_TO_TILEMAP EQU 1
LOCKDOWN_STAGE_LOOK_FOR_FULL_LINES EQU 2
LOCKDOWN_STAGE_BLINK               EQU 3

TYPE_A_LEVEL_COUNT EQU 10
TYPE_B_LEVEL_COUNT EQU 10
TYPE_B_HIGH_COUNT  EQU 6
SCORE_SIZE  EQU 3
HIGHSCORE_ENTRY_COUNT EQU 3
HIGHSCORE_NAME_LENGTH EQU 6
HIGHSCORE_ENTRY_SIZE  EQU HIGHSCORE_NAME_LENGTH + SCORE_SIZE

PLAYFIELD_WIDTH EQU 10

AUTOFIRE_DELAY EQU 23
AUTOFIRE_RATE  EQU 9
FASTDROP_RATE  EQU 3

INITIAL_TETROMINO_Y EQU $18
INITIAL_TETROMINO_X EQU $3f
