DemoDataTypeA::
	db 0,                 42
	db D_LEFT,             1
	db 0,                 29
	db A_BUTTON,           9
	db 0,                  7
	db A_BUTTON,          11
	db 0,                  3
	db D_LEFT,             4
	db 0,                 32
	db D_LEFT,             6
	db 0,                 10
	db D_DOWN,            23
	db 0,                  6
	db A_BUTTON,           6
	db 0,                  4
	db A_BUTTON,           5
	db 0,                 30
	db D_DOWN,            11
	db 0,                  6
	db D_DOWN,            28
	db 0,                 10
	db D_RIGHT,            8
	db D_RIGHT + A_BUTTON, 4
	db A_BUTTON,           2
	db 0,                  4
	db A_BUTTON,           6
	db 0,                  0
	db D_RIGHT,            6
	db 0,                  4
	db D_RIGHT,            5
	db 0,                 26
	db D_DOWN,            36
	db 0,                 21
	db A_BUTTON,           7
	db 0,                 32
	db D_RIGHT,            4
	db 0,                  5
	db D_RIGHT,            3
	db 0,                 13
	db D_RIGHT,            6
	db 0,                  3
	db D_RIGHT,            5
	db 0,                 37
	db D_DOWN,            21
	db 0,                 27
	db D_RIGHT,            4
	db 0,                 19
	db D_DOWN,             3
	db 0,                 28
	db D_DOWN,            25
	db 0,                 26
	db A_BUTTON,           6
	db 0,                 10
	db D_LEFT,             1
	db 0,                  9
	db D_LEFT,             2
	db 0,                 20
	db D_RIGHT,            3
	db 0,                 14
	db D_DOWN,            22
	db 0,                 10
	db D_RIGHT,           10
	db A_BUTTON + D_RIGHT, 6
	db D_RIGHT,           22
	db 0,                 19
	db D_DOWN,            37
	db 0,                 28
	db A_BUTTON,           6
	db 0,                  3
	db D_LEFT,             2
	db 0,                 14
	db D_LEFT,             3
	db 0,                  4
	db D_LEFT,             2
	db 0,                  3
	db D_LEFT,             5
	db 0,                 13
	db D_DOWN,            33
	db 0,                 19
	db A_BUTTON,           7
	db 0,                  5
	db A_BUTTON,           6
	db 0,                  4
	db A_BUTTON,           5
	db 0,                  6
	db D_LEFT,             3
	db 0,                  5
	db D_LEFT,             2
	db 0,                 28
	db D_LEFT,             3
	db 0,                 14
	db D_DOWN,            18
	db 0,                 12
	db D_RIGHT,            4
	db 0,                  2
	db A_BUTTON,           8
	db 0,                 16
	db A_BUTTON,           8
	db 0,                 30
	db D_DOWN,            25
	db 0,                 16
	db D_RIGHT,            3
	db 0,                  4
	db D_RIGHT,            5
	db 0,                 36
	db D_DOWN,            28
	db 0,                  5
	db A_BUTTON,           5
	db 0,                 17
	db D_LEFT,             3
	db 0,                 18
	db D_DOWN,            32
	db 0,                 10
	db D_RIGHT,            1
	db A_BUTTON + D_RIGHT, 6
	db A_BUTTON,           0
	db 0,                  4
	db D_RIGHT,            4
	db 0,                  4
	db D_RIGHT,            3
	db 0,                  2
	db D_RIGHT,           25
	db 0,                  4
	db D_RIGHT,            7
	db 0,                 10
	db 0,                  0
	db 0,                  0
	db 0,                  0

DemoDataTypeB::
	db 0,                 77
	db D_LEFT,             8
	db A_BUTTON + D_LEFT,  6
	db D_LEFT,            11
	db 0,                  7
	db D_LEFT,             6
	db 0,                100
	db D_RIGHT,            0
	db A_BUTTON + D_RIGHT, 6
	db D_RIGHT,            5
	db 0,                 47
	db D_DOWN,            22
	db 0,                 23
	db D_LEFT,             5
	db 0,                  6
	db D_LEFT,             6
	db 0,                 16
	db D_DOWN,            24
	db 0,                 52
	db A_BUTTON,           5
	db 0,                  1
	db D_RIGHT,           14
	db A_BUTTON + D_RIGHT, 6
	db D_RIGHT,           32
	db 0,                 10
	db D_DOWN,            10
	db 0,                 43
	db D_LEFT,             6
	db 0,                  6
	db D_LEFT,             5
	db 0,                  5
	db D_LEFT,             6
	db 0,                 10
	db D_DOWN,            12
	db 0,                 10
	db A_BUTTON,           7
	db 0,                  2
	db D_RIGHT,           11
	db 0,                  5
	db D_RIGHT,            4
	db 0,                 13
	db D_DOWN,            28
	db 0,                117
	db A_BUTTON,           6
	db 0,                 14
	db D_DOWN,            31
	db 0,                 26
	db A_BUTTON,           6
	db 0,                  0
	db D_RIGHT,            7
	db 0,                  5
	db D_RIGHT,            6
	db 0,                  4
	db D_RIGHT,            8
	db 0,                  3
	db D_RIGHT,            8
	db 0,                 12
	db D_DOWN,            15
	db 0,                 10
	db A_BUTTON,           7
	db 0,                  0
	db D_RIGHT,           61
	db 0,                  5
	db D_DOWN,            31
REPT 16
	db 0,                  0
ENDR
